apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-depl
  template:
    metadata:
      labels:
        app: mysql-depl
    spec:
      containers:
      - name: mysql-depl
        image: mysql
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "wasti786@"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-srv
spec:
  selector:
    app: mysql-depl
  ports:
  - port: 3306
    targetPort: 3306
